
# This Makefile has been automatically generated by Spellcast.
# See: https://www.npmjs.org/package/spellcast

summon:
	./bin/spellcast summon

dev-summon:
	./bin/spellcast dev-summon

clean:
	./bin/spellcast clean

test:
	./bin/spellcast test

bdd:
	./bin/spellcast bdd

hint:
	./bin/spellcast hint

publish:
	./bin/spellcast publish

npm-install:
	./bin/spellcast npm-install

npm-dev-install:
	./bin/spellcast npm-dev-install

npm-publish:
	./bin/spellcast npm-publish

upgrade-version:
	./bin/spellcast upgrade-version

check-master:
	./bin/spellcast check-master

git-push:
	./bin/spellcast git-push

bdd-spec.md:
	./bin/spellcast bdd-spec.md

README.md:
	./bin/spellcast README.md

# Make every rules 'PHONY' rules, let Spellcast handle dependencies and everything else.
.PHONY: summon dev-summon clean test bdd hint publish npm-install npm-dev-install npm-publish upgrade-version check-master git-push bdd-spec.md README.md

