/*
	Spellcast
	
	Copyright (c) 2014 - 2016 Cédric Ronvel
	
	The MIT License (MIT)
	
	Permission is hereby granted, free of charge, to any person obtaining a copy
	of this software and associated documentation files (the "Software"), to deal
	in the Software without restriction, including without limitation the rights
	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
	copies of the Software, and to permit persons to whom the Software is
	furnished to do so, subject to the following conditions:
	
	The above copyright notice and this permission notice shall be included in all
	copies or substantial portions of the Software.
	
	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
	SOFTWARE.
*/

"use strict" ;


/*
function buildMakefile( spellcastBin )
{
	var i , key , ruleList = [] , file , npmInstall , makefile = '' ;
	
	file = 'Makefile' ;
	
	if ( typeof spellcastBin !== 'string' )
	{
		npmInstall = true ;
		spellcastBin = './node_modules/spellcast/bin/spellcast' ;
	}
	
	
	// Advertise
	makefile += '\n# This Makefile has been automatically generated by Spellcast.\n# See: https://www.npmjs.org/package/spellcast\n\n' ;
	
	// Get all rules
	for ( key in this.spells ) { ruleList.push( key ) ; }
	
	for ( key in this.summons )
	{
		// Do not copy summoning that share the same key as a spellcasting
		if ( ! this.spells[ key ] && key !== file ) { ruleList.push( key ) ; }
	}
	
	// Build all rules
	for ( i = 0 ; i < ruleList.length ; i ++ )
	{
		makefile += ruleList[ i ] + ':' ;
		if ( npmInstall ) { makefile +=	' ' + spellcastBin ; }
		makefile += '\n\t' + spellcastBin + ' ' + ruleList[ i ] + '\n\n' ;
	}
	
	// If necessary, add the rule to install spellcast locally
	if ( npmInstall )
	{
		makefile +=	spellcastBin + ':\n\tnpm install spellcast\n\n' ;
	}
	
	// Make every rules 'PHONY' rules
	if ( ruleList.length )
	{
		makefile +=
			"# Make every rules 'PHONY' rules, let Spellcast handle dependencies and everything else.\n" +
			'.PHONY: ' + ruleList.join( ' ' ) ;
	}
	
	makefile += '\n\n' ;
	
	try {
		fs.writeFileSync( file , makefile ) ;
	}
	catch ( error ) {
		term.red( 'Cannot create the file ' ).italic.bold.red( file + '\n' ) ;
	}
	
	//term.magenta( 'Not coded yet.\n' ) ;
} ;
*/
